---
- name: deploy | prerequisites
  hosts: all
  become: yes
  become_user: thebleed
  vars:
    site_dir: /home/thebleed/www/thebleed.com
  tasks:
    - name: create site folder (if needed)
      file:
        path: "{{ site_dir }}"
        state: directory
    - name: clone repo
      git:
        repo: "https://github.com/delameko/thebleed.git"
        dest: "{{ site_dir }}"

